// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAa7v0aicu9xB6ORf8Xbh9DoSKK3wK2Lo',
    appId: '1:777437193293:web:50ed2fdf173efd17eb6804',
    messagingSenderId: '777437193293',
    projectId: 'plant-fc67b',
    authDomain: 'plant-fc67b.firebaseapp.com',
    storageBucket: 'plant-fc67b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqUjdCN9-RuoyuRS3RSwifPzaS7m1iCY0',
    appId: '1:777437193293:android:deb7a51c264c8383eb6804',
    messagingSenderId: '777437193293',
    projectId: 'plant-fc67b',
    storageBucket: 'plant-fc67b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2thFWO1Po7k-4avGxHBeRxcNoRmYy25Q',
    appId: '1:777437193293:ios:9781e11fc075dde1eb6804',
    messagingSenderId: '777437193293',
    projectId: 'plant-fc67b',
    storageBucket: 'plant-fc67b.appspot.com',
    iosClientId: '777437193293-v40eqjo18hq7hn9f32fmg3415aubonpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.plant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2thFWO1Po7k-4avGxHBeRxcNoRmYy25Q',
    appId: '1:777437193293:ios:9781e11fc075dde1eb6804',
    messagingSenderId: '777437193293',
    projectId: 'plant-fc67b',
    storageBucket: 'plant-fc67b.appspot.com',
    iosClientId: '777437193293-v40eqjo18hq7hn9f32fmg3415aubonpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.plant',
  );
}
